### PR TITLE
Purge cache for all domains when posts updated

### PR DESCRIPTION
**Pull request by juliobranha**

### CODE REVIEW

**Review by mboynes — CHANGES_REQUESTED** [review]
Switchboard is not a VIP-specific plugin, we shouldn't add VIP-specific functionality to it. I'd recommend making an add-on plugin for this, and add any hooks you need to the plugin (at a glance, doesn't look like this is even necessary)

**Comment by kjbenk** [comment]
@mboynes Other plugins have platform compat code baked into the plugin itself, which was the approach we took here. This code ensures that posts that are assigned multiple domains have each domain specific URLs purged on update on that update.

**Comment by mboynes** [comment]
What's the concern with pulling this code into its own plugin?

**Comment by kjbenk** [comment]
This code is specific to Switchboard to ensure proper cache invalidation when used on a VIP Go site. This code can be moved into a `vip-compat` file to make this more clear. Either way, I personally do not care if this code is not committed here, but it seems like the best place. If this code is applied elsewhere, then it will persist if someone installs this plugin on VIP without adding this extra code.

**Comment by mboynes** [comment]
There are arguments to be made for compatibility files, especially if the compatibility fix is just a few lines of code. In this case, I would say it's robust enough, and independent enough, to warrant its own plugin. As an example, [SearchPress has a VIP Go add-on plugin](https://github.com/alleyinteractive/searchpress-vip-go).

**Pull request closed without merging**
